package com.why.newsbeat.dao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.why.newsbeat.base.collect.bean.Collect;
import com.why.newsbeat.base.history.bean.History;

import com.why.newsbeat.dao.greendao.CollectDao;
import com.why.newsbeat.dao.greendao.HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final CollectDao collectDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectDaoConfig = daoConfigMap.get(CollectDao.class).clone();
        collectDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        collectDao = new CollectDao(collectDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(Collect.class, collectDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        collectDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
    }

    public CollectDao getCollectDao() {
        return collectDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
